apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: observer
  namespace: bd-g05
rules:
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  - events
  verbs:
  - get
  - list
  - watch
